In [31]:
import numpy as np

# Basic Array creation

In [32]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [33]:
a = [1,2,3.5,3]
a

[1, 2, 3.5, 3]

In [34]:
np.array(a)

array([1. , 2. , 3.5, 3. ])

In [35]:
l = [[1,2,3],[4,5,6],[7,8,9]] 
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [36]:
np.array(l) #list to 2d array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array generation function**

In [37]:
arr = np.arange(1,11,2) #1d array or vector with given range
arr

array([1, 3, 5, 7, 9])

In [38]:
arr = np.zeros((4,8)) #2d array or matrix of zero  with given r and c
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
arr = np.ones((6,6)) #2d array or matrix of one  with given r and c
arr 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

**Random Generation function**

In [41]:
np.random.rand(10)

array([0.00275933, 0.11430504, 0.50590042, 0.41003953, 0.10815068,
       0.75361521, 0.31391314, 0.94976937, 0.93816062, 0.87195868])

In [42]:
np.random.randn(10)

array([ 0.26773337,  0.51248123,  1.36271615, -0.71466827, -0.0715406 ,
       -0.00201314, -1.01974535, -0.19149282,  0.08354554,  0.04068772])

In [43]:
np.random.randint(10,20,10)

array([13, 12, 17, 19, 19, 19, 11, 14, 14, 10], dtype=int32)

**Array Attributes**

In [44]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr.shape

(3, 3)

In [46]:
arr.size

9

In [47]:
arr.dtype

dtype('int64')

**Array Methods**

In [48]:
arr = np.array([[1,-2,3],[4,8,6],[7,8,9]])
arr

array([[ 1, -2,  3],
       [ 4,  8,  6],
       [ 7,  8,  9]])

In [49]:
min=arr.min()
min

np.int64(-2)

In [50]:
arr.max()

np.int64(9)

In [51]:
print(arr.sum())

44


In [52]:
np.sum(arr,axis = 1) #row

array([ 2, 18, 24])

In [53]:
np.sum(arr,axis = 0) #col

array([12, 14, 18])

In [54]:
arr.mean()

np.float64(4.888888888888889)

In [55]:
arr.std()

np.float64(3.478327964999673)

In [56]:
arr.argmax()

np.int64(8)

In [57]:
arr.argmin()

np.int64(1)

**Reshaping and resizing**

In [58]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [59]:
arr.reshape(6,5) #reshape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [60]:
arr = arr.reshape(6,5) #resize

In [61]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])