In [3]:
import numpy as np 

****ARRAY OPERATIONS****

*Arithmetic operations*

In [4]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1,a2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [5]:
a3=a1 + a2 #size must be same
a1,a2,a3

(array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([ 7,  9, 11, 13, 15]))

In [6]:
a1 -a2 , a1*a2 , a1 / a2 , a1 // a2 #new array create for each 

(array([-5, -5, -5, -5, -5]),
 array([ 6, 14, 24, 36, 50]),
 array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]),
 array([0, 0, 0, 0, 0]))

In [7]:
 a1 ** a2 #new array create for each 

array([      1,     128,    6561,  262144, 9765625])

In [8]:
a1,a2 #since original lo kuch nhi hua

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

*Broadcasting*

In [9]:
l=[10,20,30,40]
arr=np.array(l)
arr

array([10, 20, 30, 40])

In [10]:
arr + 10 , arr-10  , arr

(array([20, 30, 40, 50]), array([ 0, 10, 20, 30]), array([10, 20, 30, 40]))

In [11]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr3 = arr2 + 10
arr2,arr3

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]]))

*Deep and Shallow copy*

In [13]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
slice = a[:5]
slice = slice *10 # copy og mai change nhi hoga in 2d make shallow copy
slice , a

(array([10, 20, 30, 40, 50]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]))

In [15]:
a[4:6] *10 , a  # copy og mai change nhi hoga

(array([50, 60]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]))

In [16]:
a
b = a #make reference
b[0] = 99 
b,a

(array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]))

In [17]:
a
b = a.copy() #make copy
b[0] = 1 
b,a

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]))

*Matrix operations*

In [18]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A, B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [19]:
A+B , A-B , A*B, A/B #new array create for each 

(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]))

In [20]:
A,B,

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [21]:
A@B #matrix multiplication

array([[19, 22],
       [43, 50]])

In [22]:
np.dot(A,B) #same as above

array([[19, 22],
       [43, 50]])

In [23]:
A ,A.T

(array([[1, 2],
        [3, 4]]),
 array([[1, 3],
        [2, 4]]))

**Advance Array Manipulation**

*Stacking Array* onlu use vector

In [24]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8]) 
a , b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [25]:
c=np.vstack((a,b)) #vertical stack same dimensional ka array hona chaihye
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
d=np.array((c,c))
d

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [27]:
np.hstack((a,b))  #horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.hstack((c,c)) 

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [29]:
np.column_stack((a,b))  #column stack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

*Splitting array*

In [30]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
a,b =np.hsplit(c,2) #horizontal split in 2 parts
a,b,a.ndim

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 2)

In [32]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [33]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [34]:
a=np.vsplit(c,4)
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
