In [1]:
import numpy as np 

**NUMPY INDEXING AND SLICING OF VECTORS**

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[0:5]

array([11, 12, 13, 14, 15])

In [4]:
arr[4:]

array([15, 16, 17, 18, 19, 20])

In [5]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [6]:
arr[4]

np.int64(15)

**NUMPY INDEXING AND SLICING OF MATRIX**

In [7]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
arr[4,3]  # or arr[4][3] for only one element

np.int64(24)

In [9]:
arr[0] #only row note only col not work  arr[,5] like this

array([1, 2, 3, 4, 5])

In [10]:
arr[3] 

array([16, 17, 18, 19, 20])

In [11]:
arr[2:5,2:4]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [12]:
arr[2:5,2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [13]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [14]:
arr[:,4] 

array([ 5, 10, 15, 20, 25, 30])

**BOOLEAN INDEXING**

In [15]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [17]:
arr2 = arr[bool_index]
arr2

array([12, 14, 16, 18, 20])

In [18]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
arr2

array([12, 14, 16, 18, 20])